cmake_minimum_required(VERSION 3.8)
project(smrcore_examples)

if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
  add_compile_options(-Wall -Wextra -Wpedantic)
endif()

find_package(ament_cmake REQUIRED)
find_package(control_msgs REQUIRED)
find_package(rclcpp REQUIRED)
find_package(rclcpp_action REQUIRED)
find_package(trajectory_msgs REQUIRED)

add_executable(follow_joint_trajectory src/follow_joint_trajectory.cpp)
target_compile_features(follow_joint_trajectory PUBLIC cxx_std_17)
ament_target_dependencies(follow_joint_trajectory
  control_msgs
  rclcpp
  rclcpp_action
  trajectory_msgs
)

install(TARGETS follow_joint_trajectory DESTINATION lib/${PROJECT_NAME})
install(DIRECTORY launch DESTINATION share/${PROJECT_NAME})

ament_package()
