<?xml version="1.0"?>
<package format="3">
  <name>smrcore_examples</name>
  <version>0.1.0</version>
  <description>SMRcore ROS 2 示例包</description>
  <maintainer email="support@smore.com">Smartmore Robotics</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>control_msgs</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_action</depend>
  <depend>trajectory_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
